name: Auto Release Notes

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_call:
    secrets:
      GEMINI_API_KEY:
        required: true

jobs:
  auto-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Pull & Rebase
        run: |
          git pull --rebase origin main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/lennardkorte/auto-release-notes.git@main

      - name: Check latest tag
        run: |
          git tag --list
      
      - name: Checkout auto-release-notes repo
        uses: actions/checkout@v3
        with:
          repository: 'lennardkorte/auto-release-notes'
          path: auto-release-notes

      - name: Run Python script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python auto-release-notes/run.py > output.txt

      - name: Display output
        run: |
          cat output.txt

      - name: Commit and push changelog
        run: |
          git add CHANGELOG.md
          git diff --cached --quiet || git commit -m "Update CHANGELOG with latest release notes"
          git push origin main