name: Auto Release Notes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Pull & Rebase
        run: |
          git pull --rebase origin main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/lennardkorte/auto-release-notes.git@main

      - name: Checkout external repository
        uses: actions/checkout@v4
        with:
          repository: 'lennardkorte/auto-release-notes'
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          path: auto-release-notes

      - name: Check latest tag
        run: |
          git tag --list
      
      - name: Run Python script
        run: |
          python auto-release-notes/run.py