name: Access Code Changes and Context

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  code_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Last Release Tag
        id: get_last_release
        run: |
          last_release_tag=$(git tag --list "v[0-9]*" --sort=-v:refname | grep -v beta | head -n 1)
          echo "Last release tag: $last_release_tag"
          echo "tag=$last_release_tag" >> $GITHUB_OUTPUT

      - name: Set up Python and run git_diff_extractor
        env:
          LAST_RELEASE_TAG: ${{ steps.get_last_release.outputs.tag }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          # Install the package if not already available
          pip install .
          # Run the extractor
          git-diff-extractor


name: Run Python Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0  # Full history

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Pull & Rebase
        run: |
          git pull --rebase origin main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python your_script.py