name: Auto Release Notes

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: lennardkorte/auto-release-notes/.github/workflows/auto_release_notes.yml@main
    secrets:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}